### ISSUE TITLE
Cached assets files should always preserve relative paths

### ISSUE THREAD

**Issue by jhuet** [neilime/zf2-assets-bundle#1]
I'm having an issue with the css rule in the ZF2 Skeleton that displays the logo as a background image : 

``` css
div.container a.brand {
    background: url("../images/zf2-logo.png") no-repeat scroll 0 10px transparent;
}
```

It relates to the path image relatively to the where the css file is. But as all css files are stored at the root of the cache directory - either in production or in dev if you specify them in a specific order like this : 

``` php
        'cachePath' => '@zfRootPath/public/assets/cache',//cache directory absolute path
        'assets' => array(
            'css' => array(
                'css/bootstrap.min.css',
                'css/style.css',
                'css/bootstrap-responsive.min.css',
            ),
        )
```

It won't find the image anymore as the final path will be : `/assets/images/zf2-logo.png` instead of `/assets/cache/images/zf2-logo.png`
